#! /usr/bin/python

import argparse


REPOSITORIES = {
    "firedrake": "git@github.com:firedrakeproject/firedrake.git",
    "PyOP2": "git@github.com:OP2/PyOP2.git"
}

parser = argparse.ArgumentParser()
parser.add_argument("repo", type="str", choices=REPOSITORIES.keys())
args = parser.parse_args()

subprocess.run(["git", "clone", REPOSITORIES[args.repo]])

